=== Champonnois/VBAToolKit/Project/VTK_files/vtkConfigurationsDTD.dtd
<!ELEMENT vtkConf (info,configuration*, module*, reference*)>
	
	<!ELEMENT info (projectName,version)>
		<!ELEMENT version(#PCDATA)>
		<!ELEMENT projectName (#PCDATA)>
	
	<!ELEMENT configuration (name,path,templatePath?,title?,comment?)>
	 <!ATTLIST configuration ID #REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT path (#PCDATA)>
		<!ELEMENT templatePath(#PCDATA)>
		<!ELEMENT title	(#PCDATA)>
		<!ELEMENT comment (#PCDATA)>
	
	<!ELEMENT module (name,path*)>
	 <!ATTLIST module ID #REQUIRED>
		<!ELEMENT modulePath(#PCDATA)>
		 <!ATTLIST modulePath 
			confID IDREF #REQUIRED 
		 >
	
	<!ELEMENT reference (name,guid | path)>
	 <!ATTLIST reference ID #REQUIRED>
		<!ELEMENT guid (#PCDATA)>

=== Champonnois/VBAToolKit/Templates/XMLExport/TestProject.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE vtkConf SYSTEM "vtkConfigurationsDTD.dtd">
<vtkConf>
	<info>
		<vtkConfigurationsVersion>1.0</vtkConfigurationsVersion>
		<projectName>TestProject</projectName>
	</info>

	<configuration cID="c01">
		<name>TestProject</name>
		<path>Delivery\TestProject.xlsm</path>
	</configuration>

	<configuration cID="c02">
		<name>TestProject_DEV</name>
		<path>Project\TestProject_DEV.xlsm</path>
	</configuration>


	<module mID="m01">
		<name>TestModule1</name>
		<modulePath confId="c02">Project\TestModule1.bas</modulePath>
	</module>


	<module mID="m02">
		<name>TestModule2</name>
		<modulePath confId="c02">Project\TestModule2.bas</modulePath>
	</module>


</vtkConf>

=== Champonnois/VBAToolKit/Templates/XMLSheetForConfigurationsTests.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE vtkConf SYSTEM "vtkConfigurationsDTD.dtd">
<vtkConf>

	<info>
		<vtkConfigurationsVersion>2.0</vtkConfigurationsVersion>
		<projectName>TestProject1</projectName>
	</info>


	<configuration cID="c01">
		<name>ExistingProject</name>
		<path>Delivery\ExistingProject.xlsm</path>
		<title>Existing Project Delivery version</title>
		<comment>This is the Delivery configuration of ExistingProject</comment>
	</configuration>

	<configuration cID="c02">
		<name>ExistingProject_DEV</name>
		<path>Project\ExistingProject_DEV.xlsm</path>
		<templatePath>Templates/TestTemplate.xlsm</templatePath>
		<title>Existing Project DEV version</title>
		<comment>This is the DEV configuration of ExistingProject</comment>
	</configuration>

	<module mID="m01">
		<name>Module1</name>
		<modulePath confId="c01">Path1Module1</modulePath>
	</module>

	<module mID="m02">
		<name>Module2</name>
		<modulePath confId="c02">Path2Module2</modulePath>
	</module>

	<module mID="m03">
		<name>Module3</name>
	</module>

	<module mID="m04">
		<name>Module4</name>
		<modulePath confId="c01">Path1Module4</modulePath>
		<modulePath confId="c02">Path2Module4</modulePath>
	</module>

	<module mID="m05">
		<name>Module5</name>
		<modulePath confId="c01"/>
		<modulePath confId="c02">Path2Module5</modulePath>
	</module>

	<reference confIDs="c01">
		<name>Reference1</name>
		<guid>GuidReference1</guid>
	</reference>

	<reference confIDs="c01 c02">
		<name>Reference2</name>
		<guid>GuidReference2</guid>
	</reference>

	<reference confIDs="c01">
		<name>Reference3</name>
		<path>PathReference3</path>
	</reference>

</vtkConf>

=== Champonnois/VBAToolKit/Templates/TestProjectForRecreateConfiguration.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE vtkConf SYSTEM "vtkConfigurationsDTD.dtd">
<vtkConf>

	<info>
		<vtkConfigurationsVersion>1.0</vtkConfigurationsVersion>
		<projectName>TestProjectForRecreateCOnfiguration</projectName>
	</info>

	<configuration cID="c01">
		<name>TestProject</name>
		<path>TestProject.xlsm</path>
	</configuration>

	<configuration cID="c02">
		<name>TestProject_DEV</name>
		<path>TestProject_DEV.xlsm</path>
	</configuration>

	<configuration cID="c03">
		<name>TestProject_notExistingPathConf1</name>
		<path>testFolder1\TestProject_notExistingPathConf1.xlsm</path>
	</configuration>

	<configuration cID="c04">
		<name>TestProject_notExistingPathConf2</name>
		<path>testFolder1\testFolder2\TestProject_notExistingPathConf2.xlsm</path>
	</configuration>

	<configuration cID="c05">
		<name>TestProject_emptyConf</name>
		<path>TestProject_emptyConf.xlsm</path>
	</configuration>

	<configuration cID="c06">
		<name>TestProject_normalConf</name>
		<path>TestProject_normalConf.xlsm</path>
	</configuration>

	<configuration cID="c07">
		<name>TestProject_xlamConf</name>
		<path>TestProject_xlamConf.xlam</path>
	</configuration>

	<configuration cID="c08">
		<name>TestProject_xlsConf</name>
		<path>TestProject_xlsConf.xls</path>
	</configuration>

	<configuration cID="c09">
		<name>TestProject_xlaConf</name>
		<path>TestProject_xlaConf.xla</path>
	</configuration>

	<configuration cID="c10">
		<name>TestProject_multitypeConf</name>
		<path>TestProject_multitypeConf.xlsm</path>
	</configuration>

	<configuration cID="c11">
		<name>TestProject_VTKConf</name>
		<path>VBAToolKit.xlam</path>
	</configuration>

	<configuration cID="c12">
		<name>VBAToolKit</name>
		<path>VBAToolKit.xlam</path>
	</configuration>


	<module mID="m01">
		<name>TestModule1</name>
		<modulePath confId="c02">TestModule1.bas</modulePath>
		<modulePath confId="c03">TestModule1.bas</modulePath>
		<modulePath confId="c04">TestModule1.bas</modulePath>
		<modulePath confId="c06">TestModule1.bas</modulePath>
		<modulePath confId="c07">TestModule1.bas</modulePath>
		<modulePath confId="c08">TestModule1.bas</modulePath>
		<modulePath confId="c09">TestModule1.bas</modulePath>
		<modulePath confId="c10">TestModule1.bas</modulePath>
		<modulePath confId="c11">TestModule1.bas</modulePath>
		<modulePath confId="c12">TestModule1.bas</modulePath>
	</module>


	<module mID="m02">
		<name>TestModule2</name>
		<modulePath confId="c02">TestModule2.bas</modulePath>
		<modulePath confId="c06">TestModule2.bas</modulePath>
		<modulePath confId="c07">TestModule2.bas</modulePath>
		<modulePath confId="c08">TestModule2.bas</modulePath>
		<modulePath confId="c09">TestModule2.bas</modulePath>
		<modulePath confId="c10">TestModule2.bas</modulePath>
		<modulePath confId="c11">TestModule2.bas</modulePath>
		<modulePath confId="c12">TestModule2.bas</modulePath>
	</module>


	<module mID="m03">
		<name>TestClassModule1</name>
		<modulePath confId="c10">TestClassModule1.cls</modulePath>
	</module>


	<module mID="m04">
		<name>TestFromModule1</name>
		<modulePath confId="c10">TestFormModule1.frm</modulePath>
	</module>

</vtkConf>

=== Champonnois/VBAToolKit/Templates/InitializedProject.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE vtkConf SYSTEM "vtkConfigurationsDTD.dtd">
<vtkConf>

	<info>
		<vtkConfigurationsVersion>2.0</vtkConfigurationsVersion>
		<projectName>InitializedProjet</projectName>
	</info>


	<configuration cID="c01">
		<name>InitializedProjet_DEV</name>
		<path>Tests\InitializedProjet_DEV.xlsm</path>
	</configuration>


	<module mID="m01">
		<name>TestModule</name>
		<modulePath confId="c01">Tests\TestModule.bas</modulePath>
	</module>

	<module mID="m02">
		<name>TestClass</name>
		<modulePath confId="c01">Tests\TestModule.cls</modulePath>
	</module>

	<module mID="m03">
		<name>TestForm</name>
		<modulePath confId="c01">Tests\TestForm.frm</modulePath>
	</module>

	<module mID="m04">
		<name>ThisWorkbook</name>
		<modulePath confId="c01">Tests\ThisWorkbook.cls</modulePath>
	</module>

</vtkConf>
